"""KPI extraction via RAG + Gemini structured output.

Uses targeted multi-query retrieval with exact line-item terminology to fetch
statement table chunks (Income Statement, Balance Sheet, Cash Flow Statement) as well as
risk factors and growth drivers before invoking Gemini for structured extraction.
"""

from pydantic import BaseModel, Field

from llm.gemini import get_structured_completion


class FinancialMetrics(BaseModel):
    """Structured financial KPIs extracted from a corporate annual report."""

    revenue: str | None = Field(
        None,
        title="Revenue",
        description="Total revenue / Total net sales for the fiscal year (match the report exactly, e.g. '$391,035 million' or '391,035').",
    )
    net_income: str | None = Field(
        None,
        title="Net Income",
        description="Net income / bottom-line profit for the fiscal year.",
    )
    operating_income: str | None = Field(
        None,
        title="Operating Income",
        description="Operating income (EBIT) for the fiscal year.",
    )
    cash_flow: str | None = Field(
        None,
        title="Cash Flow from Operating Activities",
        description="Net cash generated by / provided by operating activities.",
    )
    total_assets: str | None = Field(
        None,
        title="Total Assets",
        description="Total assets from the balance sheet.",
    )
    total_liabilities: str | None = Field(
        None,
        title="Total Liabilities",
        description="Total liabilities from the balance sheet.",
    )
    risk_factors: list[str] | str | None = Field(
        None,
        title="Top Risk Factors",
        description="The top risk factors disclosed in the annual report (concise list).",
    )
    growth_drivers: list[str] | str | None = Field(
        None,
        title="Top Growth Drivers",
        description="Key growth initiatives, product performance, or tailwinds described in the report.",
    )


TARGETED_QUERIES = [
    "Products Services Total net sales Cost of sales Gross margin Operating expenses Research and development Selling general and administrative Operating income Provision for income taxes Net income",
    "ASSETS Current assets Cash and cash equivalents Marketable securities Accounts receivable Vendor non-trade receivables Inventories Other current assets Total current assets Non-current assets Marketable securities Property plant and equipment net Other non-current assets Total non-current assets Total assets",
    "LIABILITIES AND SHAREHOLDERS EQUITY Current liabilities Accounts payable Other current liabilities Deferred revenue Commercial paper Term debt Total current liabilities Non-current liabilities Term debt Other non-current liabilities Total non-current liabilities Total liabilities",
    "Operating activities Net income Cash generated by operating activities Adjustments to reconcile net income Depreciation and amortization Share-based compensation expense",
    "Item 1A Risk Factors risk factors business risks competition supply chain legal proceedings interest rate risk foreign exchange rate risk",
    "Item 7 Management Discussion and Analysis growth drivers demand new products services iPhone Mac iPad Services",
]


def retrieve_context(
    retriever,
    company: str,
    year: int | str | None,
) -> str:
    """Retrieve targeted annual-report chunks for all key financial areas."""
    retrieved_docs = []
    seen_contents = set()

    for base_query in TARGETED_QUERIES:
        docs = retriever.invoke(
            query=base_query,
            company=company,
            year=year,
            top_k=5,
        )
        for doc in docs:
            if doc.page_content not in seen_contents:
                seen_contents.add(doc.page_content)
                retrieved_docs.append(doc)

    return "\n\n---\n\n".join(doc.page_content for doc in retrieved_docs)


def build_extraction_prompt(
    company: str,
    year: int | str | None,
    context: str,
) -> str:
    return f"""You are an expert financial analyst.

Company: {company}
Fiscal Year: {year}

Retrieved context from the annual report:
{context}

Extract the following financial information from the context above for fiscal year {year}.
Return null for any value that is not present in the context.
Do not invent or estimate values.

1. revenue – Total revenue / Total net sales for fiscal year {year}.
2. net_income – Net income for fiscal year {year}.
3. operating_income – Operating income for fiscal year {year}.
4. cash_flow – Cash generated by / provided by operating activities for fiscal year {year}.
5. total_assets – Total assets on the Balance Sheet as of fiscal year {year}.
6. total_liabilities – Total liabilities on the Balance Sheet as of fiscal year {year}.
7. risk_factors – Top risk factors disclosed in the report (concise list or null).
8. growth_drivers – Top growth drivers / performance highlights disclosed in the report (concise list or null).
"""


def extract_financial_metrics(
    retriever,
    company: str,
    year: int | str | None,
) -> FinancialMetrics | None:
    """Retrieve report context using targeted queries, then extract structured KPIs using Gemini.

    Returns a FinancialMetrics instance, or None if extraction fails.
    """
    context = retrieve_context(
        retriever=retriever,
        company=company,
        year=year,
    )

    if not context.strip():
        print(f"[kpi] No context retrieved for {company} {year}. Skipping extraction.")
        return None

    prompt = build_extraction_prompt(
        company=company,
        year=year,
        context=context,
    )

    return get_structured_completion(
        prompt=prompt,
        response_model=FinancialMetrics,
    )
